# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    container_name: postgres_schedulebot
    image: postgres:17.2-alpine3.21
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schedulebot_db
    ports:
      - "5431:5432"

#  pgadmin:
#    container_name: pgadmin4_schedulebot
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
